function disp (s)
  a = struct('massa',s.massa...
            ,'amortecimento',s.amortecimento...
            ,'rigidez',s.rigidez...
            ,'gdls',s.gdls...
            ,'nGDLs',s.nGDLs);
  disp(a);
