function b = eq (s1, s2);
  b =  isequal (s1.massa,         s2.massa) ...
    && isequal (s1.rigidez,       s2.rigidez) ...
    && isequal (s1.amortecimento, s2.amortecimento) ...
    && isequal (s1.gdls,          s2.gdls);
